stages:
  - test

server test:
  image: python:3.9-slim
  stage: test
  tags:
    - docker
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python3 -m pytest

include: '/ui/angular-workspace/.gitlab-ci.yml'