stages:
  - test-backend
  - build-frontend
  - test-frontend

server test:
  image: python:3.9-slim
  stage: test-backend
  tags:
    - docker
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python3 -m pytest

include: '/ui/angular-workspace/.gitlab-ci.yml'