unit test:
  image: node:20-bullseye
  stage: test-frontend
  tags:
    - test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
    - cd ui/angular-workspace
    - npm install -g @angular/cli@^17.3.8

  script:
    - npm ci --legacy-peer-deps
    - npm run test:ci

  artifacts:
    reports:
      junit: unit-test-results.xml

  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

build:
  image: node:20-bullseye
  stage: build-frontend
  tags:
    - docker
  before_script:
    - cd ui/angular-workspace
    - npm install -g @angular/cli@^17.3.8

  script:
    - npm ci --legacy-peer-deps
    - npm run build

  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
